language: scala
scala:
   - 2.10.4
before_install:
  # Install base Android SDK
  - sudo apt-get update -qq
  - sudo apt-get install -qq libstdc++6:i386 lib32z1 expect
  - export COMPONENTS=build-tools-19.0.3,android-19,sysimg-19,extra-android-support
  - curl -3L https://raw.github.com/embarkmobile/android-sdk-installer/version-2/android-sdk-installer | bash /dev/stdin --install=$COMPONENTS
  - source ~/.android-sdk-installer/env

  # Install required Android components
  - android update sdk --filter platform-tools,android-19,extra-android-support --no-ui --force